all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ./ansible_ssh_key
  children:
    landingpage:
      hosts:
        ansiblefuture-1.dev1.lokal:
    backend:
      hosts:
        ansiblefuture-2.dev1.lokal:
    