---
- name: Installing php-fpm
  hosts: backend
  become: yes
  vars:
    listen_ip: 127.0.0.1
    listen_port: 9000
  tasks:
  - name: install lewat yum
    yum:
      name: php-fpm
      state: latest
  - name: config untuk port
    lineinfile:
      path: /etc/php-fpm.d/www.conf
      regexp: '^listen ='
      line: 'listen = {{ listen_ip }}:{{ listen_port }}'
      state: present
  - name: Open port {{ listen_port }} for http access
    firewalld:
      port: '{{ listen_port }}/tcp'
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
  - name: Disable SELinux
    selinux:
      state: disabled
  - name: make sure php-fpm is running
    service:
      name: php-fpm
      state: restarted
