---
- name: Deploy landing page
  hosts: landingpage
  become: yes
  vars:
    my_title: "Hardika Gutama | DevOps"
    my_name: "Hardika"
    my_username: "hhhardika"
    my_username_steam: "dicka47"
    my_username_git: "hrdkgtm"
    my_username_sc: "emajor7add9"
    my_username_li: "gutamahardika"
    my_username_medium: "n0sebleedmusix"
    my_description: "DevOps Engineer | Tech Junkie | Linux Geek | Musician"
    my_theme: "indigo-white"
    #Backend vars
    backend_url: "http://ansiblefuture-2.dev1.lokal/backend.html"
  tasks:
  - name: change the content in index.html
    template:
      src: "{{ playbook_dir }}/files/landingpage.html.j2"
      dest: /var/www/html/index.html
      owner: apache
      mode: 0664
